name: CI


on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run Lint
        uses: gradle/gradle-build-action@v2.2.2
        with:
          arguments: lintDebug


      - name: Upload test report
        uses: actions/upload-artifact@v3.1.0
        with:
          name: index.html
          path: app/build/reports/lint-result-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run tests
        uses: gradle/gradle-build-action@v2.2.2
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/


  package:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: AppBrickie
        uses: DarthBenro008/app-brickie@v3.1
