name: CI
  on:
    push:
      branches: [main]
    pull_requests:
      branches: [main]
  workflow_dispatch:

  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout the code
          uses: actions/checkout@v2

        - name: Run Lint
          uses: .gradlew/lintDebug

        - name: Upload test report
          uses: actions/upload-artifacts@v2
          with:
            name: index.html
            path: app/build/reports/lint-result-debug.html
